### ISSUE TITLE
Seems like plugin sometimes screws up default clock

### ISSUE THREAD

**Issue by Dantenerosas** [joel16/PSV-VSH-Menu#33] opened 2018-07-27 19:53 UTC
I assume that "default" means working on clock developers intended. But with plugin on some games start to lag 'cause it seems that's not it. I can't say about older version but for current 3.4 it's true.

For e.g., Danganronpa 2. At the start of the second chapter there is scene with lots of objects and with plugin on and default settings (cpu "default", gpu "default: , check every 30 seconds) game lags. With plugin off it's perfect. I assume that's not the only game like that 'cause Conception 2 behaves the same.

Is there anyway not to change clock for some games except disabling plugin for them?

EDIT: Made some mistakes, corrected them

**Comment by joel16** [comment] 2018-07-27 20:14
I think its a mistake with the way I'm handling the GPU overclock. Instead of keeping it default it mistakenly underclocks for some reason. I'm going to try and fix the issue this weekend.

**Comment by Dantenerosas** [comment] 2018-07-27 20:22
Yes, that's seems to be the case. I've just checked clock through display option in plugin and in Danganronpa 2 on GPU 'default' it's 111\111 instead of 166\111 (I assume that's true default one for the game because at the very least with it that scene didn't lag when I've set to it)

Just in case check CPU code too tho I don't know if that's justified 'cause CPU clock was on 333\222 and that's seems to be default for the Vita in general

**Comment by joel16** [comment] 2018-07-27 20:47
CPU seems unaffected its the GPU that gets underclocked if you leave it at default. I'll try to get it fixed.

**Comment by Dantenerosas** [comment] 2018-07-27 21:55
Ok
By the way, mb add another item to list of clocks? I mean both GPU and CPU are missing their default clocks from list. And "default" could be just running game without setting custom clock and using provided by game.
P.S. That's not related to the issue just asking

**Comment by joel16** [comment] 2018-07-28 00:38
I'll think about it. Delete the ur0:/data/vsh folder and then install this ->https://github.com/joel16/PSV-VSH-Menu/raw/gh-pages/vsh.suprx and let me know if the issue is fixed.

**Comment by Dantenerosas** [comment] 2018-07-28 04:29
Hmm, seems like it fixes that behavior. Now it shows 166\166 mhz instead of 111\111. Mb that's how it was intended - fixed 166 mhz

**Comment by joel16** [comment] 2018-07-28 05:04
Now it only changes the clock rates if you press left/right in VSH otherwise it won't overclock.

**Comment by Dantenerosas** [comment] 2018-07-28 05:14
Nice. Thank you for quick fix, by the way

**Comment by joel16** [comment] 2018-07-28 05:15
No problem, I'll look into your other suggestion earlier. Anyways this is fixed now.

**Closed as completed by joel16** 2018-07-28 05:15 UTC
